### ISSUE TITLE
Avatar alt text

### ISSUE THREAD

**Issue by AverageHelper** [pyrox0/fursona-schema#11]
It may be useful, when building a site to display the contents of one's fursona.json file, to present the avatar as an image. People on slow internet connections and people with limited vision may want a way to consume that image with more descriptive text than "{name} avatar image".

Something I'm trying in my own file, since the schema does not preclude additional properties, is a new `avatarAlt` property. The purpose of this property is, if provided, for the given string to be used to describe the `avatar` image, perhaps as the `alt` property of an `<img>` tag, or an `aria-label` for a different element.

I've considered also a `refAlt` property, but I figure the `description` field may suffice already, considering the detailed character ref as well as the `colors` array may be best suited to sighted artists. However, if visually-impaired artists can make use of a ref somehow, and would benefit from a dedicated `refAlt` property, then I'm not at all opposed to one being added to the schema!

**Comment by pyrox0** [comment]
This is a great idea! I'll add both properties, since they're optional, if someone doesn't need one, they don't need to add one

**Comment by pyrox0** [comment]
I've added this and tagged version 1.1. Thank you very much for the suggestions! I didn't even think about adding these when creating the schema, and it's definitely something that should have been added!
